# This is the Makefile for DSA HW4 program part
# Author: b03902048
all: tree forest
CC = g++
INSTDIR = /usr/local/bin
CFLAGS = -O2 -Wall

tree: 4-2-2.cpp
	$(CC) $(CFLAGS) -o tree 4-2-2.cpp

forest: 4-2-6.cpp
	$(CC) $(CFLAGS) -o forest 4-2-6.cpp

clean:
	rm -rf tree forest

